### ISSUE TITLE
Holá Amigo!

### ISSUE THREAD

**Issue by puelon** [jlozoya/ionic-bluetooth-serial-example#1]
Holá amigo, saludos de brazil, estoy usando ese code y necessito ayuda. Pelo que veo no me puedo conectar a los otros androids? ejemplo: si tiengo 2 dispositivos androids no puedo conectarlos pero, mi duda es, si tiengo un HC-06 bluetooth y un android, puedo conectarlos?

**Comment by jlozoya** [comment]
Perdón no había visto tu mensaje, mejor tarde que nunca, este ejemplo implementa esta librería https://github.com/don/BluetoothSerial en la portada de dicha librería explica los limitantes de la misma. Respondiendo a tu pregunta un HC-06 y un android los puedes conectar sin problemas.
